version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: "14"
  - package-ecosystem: gradle
    directory: "/config-holder"
    schedule:
      interval: daily
    target-branch: "14"
